### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by dkdbProjects** [dkdbProjects/server-result-sender#1]
Как обычно, мне лень на англ
Итерация 1. Работа с отправкой данных с сервера на клиент
Задача: в клиенте отобразить на карте данные с сервера
Требования: 
- [x] сервер на питоне и размещен на хостинге (надо у Никитки спросить, у него есть хороший варик, котокрый мы использовали в киллере)
- [x] клиент HTML/JS/CSS на базе collector
- [ ] Удалить вывод всех лишних данных, оставить только вывод с акса, компаса и гироскопа и кнопку фикс.
- [ ] Добавить кнопки для режимов - определение местположения или отображение дефектов.
- [ ] Добавить возможность быстрого старта и остановки всех датчиков в зависимости от режима.
- [x] Данные передаются в JSON
- [x] Отображение результатов на карте (рисование линий)
- [x] Добавить кнопку очистки карты
- [x] Запрос get_position POST - расчет положения по данным 
     Параметры: acc_data, tim_data, com_data, lat, lon, speed, values
     Результат: lat, lon, speed
- [ ] Запрос get_road_defect_maps GET
     Результат: colored polylines
- [ ] Запрос send_road_defect_data POST - расчет положения по данным 
     Параметры: gps_data, acc_data, com_data, def_data, tim_data, values
     Результат: none or colored polylines for last position
